-- Chronicle Finance Database Setup
-- Run this script in the Supabase SQL Editor

-- 1. Create the simulations table
CREATE TABLE IF NOT EXISTS public.simulations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    model_type TEXT NOT NULL,
    parameters JSONB NOT NULL,
    results JSONB NOT NULL,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.simulations ENABLE ROW LEVEL SECURITY;

-- 3. Create RLS Policies

-- Policy: Users can view their own simulations
CREATE POLICY "Users can view their own simulations" 
ON public.simulations
FOR SELECT 
USING (auth.uid() = user_id);

-- Policy: Users can insert their own simulations
CREATE POLICY "Users can insert their own simulations" 
ON public.simulations
FOR INSERT 
WITH CHECK (auth.uid() = user_id);

-- Policy: Users can update their own simulations
CREATE POLICY "Users can update their own simulations" 
ON public.simulations
FOR UPDATE 
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Policy: Users can delete their own simulations
CREATE POLICY "Users can delete their own simulations" 
ON public.simulations
FOR DELETE 
USING (auth.uid() = user_id);

-- 4. Create an index on user_id for faster lookups
CREATE INDEX IF NOT EXISTS idx_simulations_user_id ON public.simulations(user_id);
